FROM python:3.9-slim-bullseye
RUN apt-get update -y && apt-get install -y libasound2 python3-pip build-essential wget

# install python dependencies
RUN pip3 install --upgrade pip
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt && pip3 cache purge

# copy files
COPY cloudlanguagetools_chatbot/ cloudlanguagetools_chatbot/
COPY telegram_app.py ./

# start
ENTRYPOINT ["python3", "telegram_app.py"]
